template: |
  _[ADD SUMMARY OF WHAT CHANGED]_

  ## What's Changed

  _[IF PR'S TITLE IS NOT EXPLICIT ENOUGH, ADD DETAILS TO IT]_
  $CHANGES

  ## Impact On Gear Outputs

  _[LIST HOW STRUCTURE AND/OR VALUES OF GEAR OUTPUTS (e.g. FILES AND METADATA) ARE IMPACTED]_
